name: GitHub Actions Demo
run-name: GITHUB ACTOR*** ${{ github.actor }} is testing out GitHub Actions ğŸš€
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a GITHUB EVENT*** ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a RUNNER OS*** ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is GITHUB REF*** ${{ github.ref }} and your repository is GITHUB REPO*** ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "ğŸ’¡ The GITHUB REPO_*** ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "ğŸ This job's status is JOB STATUS*** ${{ job.status }}."
